---
title: "Final Project"
author: "Danielle Jones & Katie Perez"
format: html
editor: visual
  highlight-style: pygments
syntax: tango
execute: 
  echo: true
  message: false
  warning: false
fig-width: 9
fig-height: 7
bibliography: references.bib
link-citations: true
---

# Load libraries

```{r}
library(here)
library(rio)
library(tidyverse)
library(janitor)
library(ggthemes)
library(gghighlight)
library(tidyr)

```

# Load data

```{r}
here("data", "Olympic_Swimming_Results_1912to2020.csv")

olyswim <- read_csv(here("data", "Olympic_Swimming_Results_1912to2020.csv")) %>%
  characterize() %>%
  clean_names()
```

# Cleaning/organizing data

```{r}
olyswim <- olyswim %>%
  filter(year >= 1919, year <=2020,
         relay == 0, rank != 0, rank !=4, rank !=5) %>%
  select(-location, -relay) %>%

  mutate(foo = str_replace_all(results, "\\.", ":")) %>%
  separate_wider_delim(foo, ":", names = c("h", "m", "s", "ms"), too_few = "align_end") %>%
  mutate(across(c(h:ms), as.numeric),
         across(c(h:ms), ~as.numeric(ifelse(is.na(.), "0", .))),
         results_sec = case_when(
           s == 0 ~ as.character(ms),
           s!= 0 ~ paste0((h * 360) + (m * 60) + (s), ".", ms)
         ),
         results_sec = as.numeric(results_sec))
  
```

# Creating gender and stroke dataframe
```{r}
olyswimgenderstroke <- olyswim %>%
  group_by(gender, stroke) %>%
  summarise(mean_time = mean(results))

summarize(olyswimgenderstroke)
```

